### ISSUE TITLE
remove the grey background for white theme

### ISSUE THREAD

**Issue by fnaji** [tercen/volcano_shiny_operator#1]

**Comment by teofiln** [comment]
Hi @fnaji, I just pushed an update that addresses the grey background for that container ( https://github.com/teofiln/volcano_shiny_operator-1/commit/7055319d4048f5f59df8635a308e4dbbb8496390 ). I created another release v0.0.6.3 that has these changes. Please have a look and let me know if something else needs attention. Thanks.
